"""Add phone and address to invoice

Revision ID: f4c2173fea19
Revises: 68a0c78a8acb
Create Date: 2025-11-14 13:35:27.881804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c2173fea19'
down_revision = '68a0c78a8acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('customer_address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('customer_address')
        batch_op.drop_column('customer_phone')

    # ### end Alembic commands ###
